; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env_base]
platform = ststm32
platform_packages = 
	framework-arduinoststm32 @ https://github.com/stm32duino/Arduino_Core_STM32.git
board = genericSTM32G431CB
framework = arduino
upload_protocol = dfu
lib_archive = false
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
	-D HAL_PCD_MODULE_ENABLED
	-D USB_MANUFACTURER="Unknown"
	-D USB_PRODUCT="\"G4321\""
	-D USBD_VID=0x0483
	-D USBD_PID=0x5740
	
	-D HSE_VALUE=16000000UL
	-D USE_HSE_CLOCK
	
	-D PIN_WIRE_SDA=PB7
	-D PIN_WIRE_SCL=PA15

	-D LED_BUILTIN=PC14
	
	-D HAL_CORDIC_MODULE_ENABLED
	-D ARDUINO_GENERIC_G431CBTX

	-I /home/trough/.platformio/packages/framework-cmsis-dsp/Include

lib_deps = 
	askuric/Simple FOC@^2.4.0
	simplefoc/SimpleFOCDrivers@^1.0.9
	


[env:Left]
extends = env_base
build_flags = 
	${env_base.build_flags}
	-D IS_RIGHT=0
	-D I2C_ADDR=0x20

[env:Right]
extends = env_base
build_flags = 
	${env_base.build_flags}
	-D IS_RIGHT=1
	-D I2C_ADDR=0x21